modLoader="javafml"

loaderVersion="[45,)"
license="AMIT"


[[mods]]
# The modid of the mod
modId="combataugments"

version="0.1.0"

displayName="Combatant's Augments"

#updateJSONURL="https://change.me.example.invalid/updates.json" #optional


#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional


logoFile="combataugments.png"

#credits=""


authors="FuyuVulpes"


description='''
A Mod that intends on adding to Minecraft's Combat variety as well as expand on its Exploration aspects
'''


[[dependencies.combataugments]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"


[[dependencies.combataugments]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"

[[dependencies.combataugments]]
    modId="geckolib"
    mandatory=true
    versionRange="[4.1.3,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.combataugments]]
    modId="sherdsapi"
    mandatory=true
    versionRange="[3.0.2,)"
    ordering="NONE"
    side="BOTH"
